using System;
using System.Collections.Generic;
using System.Globalization;
public sealed class CheckpointLanguage {
 public string Code, NativeName; public string[] Text;
}
public static class CheckpointLocalization {
 public static readonly string[] Keys={"Error","Ready","Saved","NoSave","Loaded","ConfigError","KeyError","Bar","ConfirmTitle","SettingsTitle","ConfirmBody","LastSave","Confirm","Cancel","ConfirmToggle","BarToggle","SaveKey","LoadKey","BindHint","SettingsHint","Reset","Close","Language","ChooseTitle","ChooseHint","Continue","ConfirmKeyHint"};
 public static readonly CheckpointLanguage[] Languages;
 static readonly Dictionary<string,CheckpointLanguage> Lookup=new Dictionary<string,CheckpointLanguage>();
 static CheckpointLocalization() {
  var items=new List<CheckpointLanguage>();
  foreach(string line in Data.Split(new char[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries)) {
   var parts=line.Split('|'); if(parts.Length!=Keys.Length+2) throw new Exception("Translation column mismatch: "+parts[0]+" "+parts.Length);
   var text=new string[Keys.Length]; Array.Copy(parts,2,text,0,text.Length);
   var language=new CheckpointLanguage {Code=parts[0],NativeName=parts[1],Text=text}; items.Add(language); Lookup.Add(language.Code,language);
  }
  Languages=items.ToArray();
 }
 public static bool Has(string language) {return language!=null && Lookup.ContainsKey(language);}
 public static string Get(string language,string key,params object[] arguments) {
  int index=Array.IndexOf(Keys,key); if(index<0) throw new ArgumentException("Unknown translation key: "+key);
  CheckpointLanguage item; if(!Lookup.TryGetValue(language??"en",out item)) item=Lookup["en"];
  return string.Format(CultureInfo.InvariantCulture,item.Text[index],arguments);
 }
 public static string Name(string language) {CheckpointLanguage item; return Lookup.TryGetValue(language??"en",out item)?item.NativeName:"English";}
 const string Data=@"en|English|Operation failed; see Player.log|QuickCheckpoint ready · F10 Settings|Checkpoint saved|No checkpoint yet; press {0}|Checkpoint loaded|Failed to save settings|Key reserved or already in use|{0} Save · {1} Load · F10 Settings|Save checkpoint?|QuickCheckpoint settings|Save the position captured on the first key press. This replaces your checkpoint.|Last checkpoint: {0}|Save|Cancel|Confirm before saving|Show status bar|Save key|Load key|Press a new key; Esc cancels.|F10 opens settings. Settings persist when closed.|Reset defaults|Save and close|Language|Choose your language|Select a language. You can change it later in F10 settings.|Continue|Press {0} again to confirm, or click Save.
zh-Hans|简体中文|操作失败，请查看 Player.log|快捷存档已启用 · F10 设置|存档成功|还没有存档，请先按 {0}|已回到存档位置|设置保存失败|按键不可用或与其他快捷键冲突|{0} 存档 · {1} 回档 · F10 设置|确认存档|快捷存档设置|保存第一次按下存档键时的位置。已有存档将被覆盖。|上次存档：{0}|确认存档|取消|存档前弹出确认窗口|显示左上角状态条|存档按键|读档按键|请按新按键；Esc 取消。|F10 打开设置，关闭窗口后自动保存。|恢复默认|保存并关闭|语言|选择界面语言|请选择语言，之后可以在 F10 设置里更改。|继续|再按一次 {0} 确认，或点击确认存档。
zh-Hant|繁體中文|操作失敗，請查看 Player.log|快捷存檔已啟用 · F10 設定|存檔成功|還沒有存檔，請先按 {0}|已回到存檔位置|設定儲存失敗|按鍵無法使用或與其他快捷鍵衝突|{0} 存檔 · {1} 讀檔 · F10 設定|確認存檔|快捷存檔設定|儲存第一次按下存檔鍵時的位置。現有存檔將被覆蓋。|上次存檔：{0}|確認存檔|取消|存檔前顯示確認視窗|顯示左上角狀態列|存檔按鍵|讀檔按鍵|請按新按鍵；Esc 取消。|F10 開啟設定，關閉視窗後自動儲存。|恢復預設|儲存並關閉|語言|選擇介面語言|請選擇語言，之後可在 F10 設定中變更。|繼續|再按一次 {0} 確認，或點擊確認存檔。
fr|Français|Échec de l’opération ; voir Player.log|QuickCheckpoint prêt · F10 Paramètres|Point de contrôle enregistré|Aucune sauvegarde ; appuyez sur {0}|Point de contrôle chargé|Échec de l’enregistrement des paramètres|Touche réservée ou déjà utilisée|{0} Sauver · {1} Charger · F10 Options|Enregistrer le point de contrôle ?|Paramètres QuickCheckpoint|Enregistre la position au premier appui. Le point de contrôle précédent sera remplacé.|Dernière sauvegarde : {0}|Enregistrer|Annuler|Confirmer avant d’enregistrer|Afficher la barre d’état|Touche de sauvegarde|Touche de chargement|Appuyez sur une touche ; Échap annule.|F10 ouvre les paramètres. Ils sont enregistrés à la fermeture.|Réinitialiser|Enregistrer et fermer|Langue|Choisissez votre langue|Choisissez une langue. Vous pourrez la modifier avec F10.|Continuer|Appuyez à nouveau sur {0} pour confirmer, ou cliquez sur Enregistrer.
es|Español|Error; consulta Player.log|QuickCheckpoint listo · F10 Ajustes|Punto de control guardado|No hay partida guardada; pulsa {0}|Punto de control cargado|No se pudieron guardar los ajustes|Tecla reservada o ya utilizada|{0} Guardar · {1} Cargar · F10 Ajustes|¿Guardar el punto de control?|Ajustes de QuickCheckpoint|Guarda la posición de la primera pulsación. Se reemplazará el punto de control anterior.|Último guardado: {0}|Guardar|Cancelar|Confirmar antes de guardar|Mostrar barra de estado|Tecla para guardar|Tecla para cargar|Pulsa una tecla; Esc cancela.|F10 abre los ajustes. Se guardan al cerrar.|Restablecer|Guardar y cerrar|Idioma|Elige tu idioma|Elige un idioma. Podrás cambiarlo en los ajustes con F10.|Continuar|Pulsa {0} otra vez para confirmar o haz clic en Guardar.
pt|Português|Falha na operação; veja Player.log|QuickCheckpoint pronto · F10 Opções|Ponto de controle salvo|Nenhum salvamento; pressione {0}|Ponto de controle carregado|Falha ao salvar as configurações|Tecla reservada ou já em uso|{0} Salvar · {1} Carregar · F10 Opções|Salvar ponto de controle?|Configurações do QuickCheckpoint|Salva a posição do primeiro toque. O ponto de controle anterior será substituído.|Último salvamento: {0}|Salvar|Cancelar|Confirmar antes de salvar|Mostrar barra de status|Tecla para salvar|Tecla para carregar|Pressione uma tecla; Esc cancela.|F10 abre as configurações. Elas são salvas ao fechar.|Restaurar padrão|Salvar e fechar|Idioma|Escolha seu idioma|Escolha um idioma. Você poderá alterá-lo com F10.|Continuar|Pressione {0} novamente para confirmar ou clique em Salvar.
de|Deutsch|Vorgang fehlgeschlagen; siehe Player.log|QuickCheckpoint bereit · F10 Optionen|Kontrollpunkt gespeichert|Noch kein Speicherstand; drücke {0}|Kontrollpunkt geladen|Einstellungen konnten nicht gespeichert werden|Taste reserviert oder bereits belegt|{0} Speichern · {1} Laden · F10 Optionen|Kontrollpunkt speichern?|QuickCheckpoint-Einstellungen|Speichert die Position beim ersten Tastendruck. Der bisherige Kontrollpunkt wird ersetzt.|Zuletzt gespeichert: {0}|Speichern|Abbrechen|Speichern bestätigen|Statusleiste anzeigen|Taste zum Speichern|Taste zum Laden|Neue Taste drücken; Esc bricht ab.|F10 öffnet die Einstellungen. Beim Schließen werden sie gespeichert.|Standardwerte|Speichern und schließen|Sprache|Sprache auswählen|Wähle eine Sprache. Du kannst sie später mit F10 ändern.|Weiter|Drücke erneut {0} oder klicke auf Speichern.
it|Italiano|Operazione non riuscita; vedi Player.log|QuickCheckpoint pronto · F10 Opzioni|Checkpoint salvato|Nessun salvataggio; premi {0}|Checkpoint caricato|Impossibile salvare le impostazioni|Tasto riservato o già in uso|{0} Salva · {1} Carica · F10 Opzioni|Salvare il checkpoint?|Impostazioni QuickCheckpoint|Salva la posizione alla prima pressione. Il checkpoint precedente verrà sostituito.|Ultimo salvataggio: {0}|Salva|Annulla|Conferma prima di salvare|Mostra la barra di stato|Tasto di salvataggio|Tasto di caricamento|Premi un nuovo tasto; Esc annulla.|F10 apre le impostazioni. Si salvano alla chiusura.|Ripristina|Salva e chiudi|Lingua|Scegli la lingua|Scegli una lingua. Potrai cambiarla in seguito con F10.|Continua|Premi di nuovo {0} per confermare o fai clic su Salva.
nl|Nederlands|Bewerking mislukt; zie Player.log|QuickCheckpoint gereed · F10 Instellingen|Controlepunt opgeslagen|Nog geen opslag; druk op {0}|Controlepunt geladen|Instellingen opslaan mislukt|Toets gereserveerd of al in gebruik|{0} Opslaan · {1} Laden · F10 Opties|Controlepunt opslaan?|QuickCheckpoint-instellingen|Slaat de positie bij de eerste toetsdruk op. Het vorige controlepunt wordt vervangen.|Laatst opgeslagen: {0}|Opslaan|Annuleren|Bevestigen vóór opslaan|Statusbalk tonen|Toets voor opslaan|Toets voor laden|Druk op een nieuwe toets; Esc annuleert.|F10 opent de instellingen. Ze worden bij sluiten opgeslagen.|Standaardwaarden|Opslaan en sluiten|Taal|Kies je taal|Kies een taal. Je kunt deze later met F10 wijzigen.|Doorgaan|Druk nogmaals op {0} of klik op Opslaan.
pl|Polski|Operacja nie powiodła się; zobacz Player.log|QuickCheckpoint gotowy · F10 Ustawienia|Punkt kontrolny zapisany|Brak zapisu; naciśnij {0}|Punkt kontrolny wczytany|Nie udało się zapisać ustawień|Klawisz zarezerwowany lub już używany|{0} Zapis · {1} Odczyt · F10 Opcje|Zapisać punkt kontrolny?|Ustawienia QuickCheckpoint|Zapisuje pozycję z pierwszego naciśnięcia. Poprzedni punkt kontrolny zostanie zastąpiony.|Ostatni zapis: {0}|Zapisz|Anuluj|Potwierdzaj zapis|Pokaż pasek stanu|Klawisz zapisu|Klawisz odczytu|Naciśnij nowy klawisz; Esc anuluje.|F10 otwiera ustawienia. Są zapisywane przy zamknięciu.|Domyślne|Zapisz i zamknij|Język|Wybierz język|Wybierz język. Możesz go później zmienić klawiszem F10.|Dalej|Naciśnij ponownie {0} lub kliknij Zapisz.
ru|Русский|Ошибка операции; см. Player.log|QuickCheckpoint готов · F10 Настройки|Контрольная точка сохранена|Нет сохранения; нажмите {0}|Контрольная точка загружена|Не удалось сохранить настройки|Клавиша зарезервирована или занята|{0} Сохранить · {1} Загрузить · F10 Опции|Сохранить контрольную точку?|Настройки QuickCheckpoint|Сохраняет позицию при первом нажатии. Предыдущая контрольная точка будет заменена.|Последнее сохранение: {0}|Сохранить|Отмена|Подтверждать сохранение|Показать строку состояния|Клавиша сохранения|Клавиша загрузки|Нажмите новую клавишу; Esc отменяет.|F10 открывает настройки. Они сохраняются при закрытии.|По умолчанию|Сохранить и закрыть|Язык|Выберите язык|Выберите язык. Позже его можно изменить через F10.|Продолжить|Нажмите {0} ещё раз или кнопку сохранения.
uk|Українська|Помилка операції; див. Player.log|QuickCheckpoint готовий · F10 Налаштування|Контрольну точку збережено|Немає збереження; натисніть {0}|Контрольну точку завантажено|Не вдалося зберегти налаштування|Клавішу зарезервовано або вже зайнято|{0} Зберегти · {1} Завантажити · F10 Опції|Зберегти контрольну точку?|Налаштування QuickCheckpoint|Зберігає позицію першого натискання. Попередню контрольну точку буде замінено.|Останнє збереження: {0}|Зберегти|Скасувати|Підтверджувати збереження|Показати рядок стану|Клавіша збереження|Клавіша завантаження|Натисніть нову клавішу; Esc скасовує.|F10 відкриває налаштування. Вони зберігаються при закритті.|Типові|Зберегти й закрити|Мова|Виберіть мову|Виберіть мову. Пізніше її можна змінити через F10.|Продовжити|Натисніть {0} ще раз або кнопку збереження.
tr|Türkçe|İşlem başarısız; Player.log dosyasına bakın|QuickCheckpoint hazır · F10 Ayarlar|Kontrol noktası kaydedildi|Kayıt yok; {0} tuşuna basın|Kontrol noktası yüklendi|Ayarlar kaydedilemedi|Tuş ayrılmış veya zaten kullanılıyor|{0} Kaydet · {1} Yükle · F10 Ayarlar|Kontrol noktası kaydedilsin mi?|QuickCheckpoint ayarları|İlk tuş basımındaki konumu kaydeder. Önceki kontrol noktası değiştirilecektir.|Son kayıt: {0}|Kaydet|İptal|Kaydetmeden önce onay iste|Durum çubuğunu göster|Kaydetme tuşu|Yükleme tuşu|Yeni tuşa basın; Esc iptal eder.|F10 ayarları açar. Kapatıldığında kaydedilir.|Varsayılanlar|Kaydet ve kapat|Dil|Dilinizi seçin|Bir dil seçin. Daha sonra F10 ile değiştirebilirsiniz.|Devam|Onaylamak için {0} tuşuna tekrar basın veya Kaydet'e tıklayın.
ja|日本語|操作に失敗しました。Player.log を確認してください|QuickCheckpoint 有効 · F10 設定|チェックポイントを保存しました|保存データがありません。{0} を押してください|チェックポイントを読み込みました|設定の保存に失敗しました|予約済み、または使用中のキーです|{0} 保存 · {1} 読込 · F10 設定|チェックポイントを保存しますか？|QuickCheckpoint 設定|最初にキーを押したときの位置を保存します。以前のチェックポイントは上書きされます。|前回の保存：{0}|保存|キャンセル|保存前に確認する|ステータスバーを表示|保存キー|読込キー|新しいキーを押してください。Esc で取消。|F10 で設定を開きます。閉じると設定が保存されます。|初期設定に戻す|保存して閉じる|言語|言語を選択|言語を選んでください。後から F10 で変更できます。|続ける|{0} をもう一度押すか、「保存」をクリックしてください。
ko|한국어|작업 실패. Player.log를 확인하세요|QuickCheckpoint 활성화 · F10 설정|체크포인트를 저장했습니다|저장된 체크포인트가 없습니다. {0} 키를 누르세요|체크포인트를 불러왔습니다|설정을 저장하지 못했습니다|예약되었거나 이미 사용 중인 키입니다|{0} 저장 · {1} 불러오기 · F10 설정|체크포인트를 저장할까요?|QuickCheckpoint 설정|처음 키를 눌렀을 때의 위치를 저장합니다. 이전 체크포인트를 덮어씁니다.|마지막 저장: {0}|저장|취소|저장 전에 확인|상태 표시줄 표시|저장 키|불러오기 키|새 키를 누르세요. Esc로 취소합니다.|F10으로 설정을 엽니다. 닫으면 설정이 저장됩니다.|기본값 복원|저장 후 닫기|언어|언어 선택|언어를 선택하세요. 나중에 F10 설정에서 변경할 수 있습니다.|계속|{0} 키를 다시 누르거나 저장 버튼을 클릭하세요.
id|Bahasa Indonesia|Operasi gagal; lihat Player.log|QuickCheckpoint siap · F10 Pengaturan|Titik simpan disimpan|Belum ada simpanan; tekan {0}|Titik simpan dimuat|Gagal menyimpan pengaturan|Tombol dicadangkan atau sudah digunakan|{0} Simpan · {1} Muat · F10 Pengaturan|Simpan titik ini?|Pengaturan QuickCheckpoint|Menyimpan posisi saat tombol pertama kali ditekan. Titik simpan sebelumnya akan diganti.|Simpanan terakhir: {0}|Simpan|Batal|Konfirmasi sebelum menyimpan|Tampilkan bilah status|Tombol simpan|Tombol muat|Tekan tombol baru; Esc membatalkan.|F10 membuka pengaturan. Pengaturan disimpan saat ditutup.|Setelan awal|Simpan dan tutup|Bahasa|Pilih bahasa Anda|Pilih bahasa. Anda dapat mengubahnya nanti melalui F10.|Lanjutkan|Tekan {0} lagi untuk mengonfirmasi atau klik Simpan.
vi|Tiếng Việt|Thao tác thất bại; xem Player.log|QuickCheckpoint sẵn sàng · F10 Cài đặt|Đã lưu điểm kiểm tra|Chưa có bản lưu; nhấn {0}|Đã tải điểm kiểm tra|Không thể lưu cài đặt|Phím được dành riêng hoặc đã được dùng|{0} Lưu · {1} Tải · F10 Cài đặt|Lưu điểm kiểm tra?|Cài đặt QuickCheckpoint|Lưu vị trí lúc nhấn phím lần đầu. Điểm kiểm tra trước đó sẽ bị thay thế.|Lần lưu gần nhất: {0}|Lưu|Hủy|Xác nhận trước khi lưu|Hiện thanh trạng thái|Phím lưu|Phím tải|Nhấn phím mới; Esc để hủy.|F10 mở cài đặt. Cài đặt được lưu khi đóng.|Mặc định|Lưu và đóng|Ngôn ngữ|Chọn ngôn ngữ|Chọn ngôn ngữ. Bạn có thể đổi sau trong cài đặt F10.|Tiếp tục|Nhấn {0} lần nữa để xác nhận hoặc nhấp Lưu.
ar|العربية|فشلت العملية؛ راجع Player.log|QuickCheckpoint جاهز · F10 الإعدادات|تم حفظ نقطة التحقق|لا يوجد حفظ؛ اضغط {0}|تم تحميل نقطة التحقق|تعذر حفظ الإعدادات|المفتاح محجوز أو مستخدم بالفعل|{0} حفظ · {1} تحميل · F10 إعدادات|هل تريد حفظ نقطة التحقق؟|إعدادات QuickCheckpoint|يحفظ الموقع عند الضغط الأول. سيتم استبدال نقطة التحقق السابقة.|آخر حفظ: {0}|حفظ|إلغاء|التأكيد قبل الحفظ|إظهار شريط الحالة|مفتاح الحفظ|مفتاح التحميل|اضغط مفتاحًا جديدًا؛ Esc للإلغاء.|يفتح F10 الإعدادات. تُحفظ عند الإغلاق.|الإعدادات الافتراضية|حفظ وإغلاق|اللغة|اختر لغتك|اختر لغة. يمكنك تغييرها لاحقًا من إعدادات F10.|متابعة|اضغط {0} مرة أخرى للتأكيد أو انقر على حفظ.";
}
